logging:
  version: 1
  disable_existing_loggers: False

  formatters:
    formatter:
      "()": coloredlogs.ColoredFormatter
      format: "[%(asctime)s] [%(name)s] [%(levelname)s] [%(threadName)s] [%(thread)d] %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: $LOG_LEVEL|DEBUG
      formatter: formatter
      stream: ext://sys.stdout

  loggers:
    sse_starlette.sse:
      level: INFO
      handlers: [console]
      propagate: False

  root:
    level: $LOG_LEVEL|DEBUG
    handlers: [console]

server:
  host: $HOST|"0.0.0.0"
  port: $PORT|"5000"
  transport: $TRANSPORT|"streamable-http"
  name: $SERVER_NAME|"MCP Server Boilerplate"
  instructions: $SERVER_INSTRUCTIONS|"A generic MCP server boilerplate for building custom tools and integrations."
  external_api_url: $EXTERNAL_API_URL|"http://localhost:8000"
